import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignInButton } from "@clerk/nextjs";
import MotionWrapper from "./MotionWrapper";

export const metadata: Metadata = {
  title: "Obliviate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <MotionWrapper>{children}</MotionWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
