import "./globals.css";

// Context
import { QuizSetContextProvider } from "@/contexts/QuizSetContext";

// Next
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Clerk
import { ClerkProvider } from "@clerk/nextjs";

// Components
import GlobalMotionWrapper from "@/app/components/GlobalMotionWrapper";

// ShadCn
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Obliviate",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QuizSetContextProvider>
        <html lang="en" className={inter.className}>
          <body>
            <GlobalMotionWrapper>{children}</GlobalMotionWrapper>
            <Toaster />
          </body>
        </html>
      </QuizSetContextProvider>
    </ClerkProvider>
  );
}
